[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pymapme"
version = "0.0.4"
description = "functionality for mapping one model into another"
readme = "README.md"
authors = ["funnydman", "ricoms"]

[tool.poetry.build]
generate-setup-file = false

[tool.pytest.ini_options]
pythonpath = [".", "pymapme"]
testpaths = 'tests'

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.7.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.10.0"
pytest = "^8.2.2"
pytest-cov = "^5.0.0"
pylint = "^3.2.3"

[tool.pylint.messages_control]
max-line-length = 88
extension-pkg-whitelist = "pydantic"
# https://stackoverflow.com/questions/10647165/pylint-complains-on-py-test-module-pytest-has-no-raises-member
# is there a better solution?
ignored-classes = "pytest"
disable = ["missing-docstring", "fixme", "too-few-public-methods"]
